### ISSUE TITLE
Use js version of closure compiler

### ISSUE THREAD

**Issue by GGG-KILLER** [ShrimpDev/grunt-google-closure-tools-compiler#5]
As many npm packages have been using, I think that by using the [js version](https://github.com/google/closure-compiler-js) of the closure compiler would be better because of:
- No need to deal with path changes of `node_modules`
- No need to have Java installed on your computer
- No need to depend on another process

**Comment by Kristinita** [comment]
The JS version of closure-compiler is no longer supported or maintained.

See [**details**](https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler-js/readme.md).

Thanks.
